project_id = "ifikgxpbdcjferbcomjy"

[functions.analyze-finances]
verify_jwt = false

[functions.compare-investments]
verify_jwt = false

[functions.extract-receipt]
verify_jwt = false

[functions.yahoo-finance]
verify_jwt = false
